-- Run once in the VMVirreira project SQL Editor.
-- Uses Dayboard's existing server-controlled admin group for writes.
begin;
create table if not exists public.driftr_categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (length(trim(name)) between 1 and 100)
);
create table if not exists public.driftr_country_audio (
  id bigint generated by default as identity primary key,
  country_name text not null unique check (length(trim(country_name)) between 1 and 100),
  mp3_link text not null check (mp3_link ~ '^https://[^/[:space:]]+/.+'),
  category_id bigint references public.driftr_categories(id) on delete set null
);
alter table public.driftr_categories enable row level security;
alter table public.driftr_country_audio enable row level security;
grant select on public.driftr_categories, public.driftr_country_audio to anon, authenticated;
grant insert, update, delete on public.driftr_categories, public.driftr_country_audio to authenticated;
grant usage, select on sequence public.driftr_categories_id_seq, public.driftr_country_audio_id_seq to authenticated;
drop policy if exists "driftr public read" on public.driftr_categories;
create policy "driftr public read" on public.driftr_categories for select to anon, authenticated using (true);
drop policy if exists "driftr admin writes" on public.driftr_categories;
create policy "driftr admin writes" on public.driftr_categories for all to authenticated
  using ((auth.jwt() -> 'app_metadata' -> 'dayboard_groups') @> '["admin"]'::jsonb)
  with check ((auth.jwt() -> 'app_metadata' -> 'dayboard_groups') @> '["admin"]'::jsonb);
drop policy if exists "driftr public read" on public.driftr_country_audio;
create policy "driftr public read" on public.driftr_country_audio for select to anon, authenticated using (true);
drop policy if exists "driftr admin writes" on public.driftr_country_audio;
create policy "driftr admin writes" on public.driftr_country_audio for all to authenticated
  using ((auth.jwt() -> 'app_metadata' -> 'dayboard_groups') @> '["admin"]'::jsonb)
  with check ((auth.jwt() -> 'app_metadata' -> 'dayboard_groups') @> '["admin"]'::jsonb);
insert into public.driftr_country_audio (country_name, mp3_link) values
  ('Bulgaria', 'https://ia902707.us.archive.org/7/items/VictorMVirreiraMusicfromBulgaria/MusicFromBulgaria.mp3'),
  ('Uruguay', 'https://ia801604.us.archive.org/20/items/VictorMVirreiraMusicfromUruguay/MusicfromUruguay.mp3'),
  ('Hungary', 'https://ia801605.us.archive.org/19/items/VictorMVirreiraMusicfromHungary/MusicFromHungary.mp3'),
  ('Malaysia', 'https://ia802209.us.archive.org/33/items/VictorMVirreiraMusicfromMalaysia/Mon2300.mp3'),
  ('Pakistan', 'https://ia600902.us.archive.org/31/items/VictorMVirreiraMusicfromPakistan/ContinentalDriftMusicfromPakistan12192005.mp3'),
  ('Greece', 'https://ia800205.us.archive.org/15/items/VictorMVirreiraMusicofGreece/ContinetalDrfitMusicFromGreece10032005.mp3'),
  ('Japan', 'https://ia803209.us.archive.org/35/items/VictorMVirreiraMusicfromJapanPart1/Mon2300.mp3'),
  ('Portugal', 'https://ia904705.us.archive.org/22/items/VictorMVirreiraMusicofPortugal/MusicOfPortugal.mp3'),
  ('Armenia', 'https://ia600909.us.archive.org/27/items/VictorMVirreiraMusicfromArmenia_0/ContinentalDriftMusicfromArmenia01162006.mp3'),
  ('Vietnam', 'https://ia601301.us.archive.org/8/items/VictorMVirreiraVietnamPart1/Mon2000.mp3'),
  ('Bolivia', 'https://ia800902.us.archive.org/8/items/VictorMVirreiraMusicfromBoliviaPart1/Mon2300.mp3'),
  ('China', 'https://ia801306.us.archive.org/11/items/VictorMVirreiraMusicfromChinaPart1/Mon2000.mp3'),
  ('Spain', 'https://ia800906.us.archive.org/32/items/VictorMVirreiraMusicfromSpain/ContinentalDriftMusicfromSpain10102005.mp3'),
  ('Iran', 'https://ia800904.us.archive.org/11/items/VictorMVirreiraMusicfromIran/ContinentalDriftMusicfromIran01232006.mp3'),
  ('United States of America', 'https://ia800106.us.archive.org/1/items/VictorMVirreiraMusicfromNewOrleans/MusicFromNewOrleans.mp3'),
  ('Romania', 'https://ia800909.us.archive.org/0/items/VictorMVirreiraMusicfromRomania/ContinentalDriftMusicfromRomania02072006.mp3'),
  ('Mexico', 'https://ia800900.us.archive.org/2/items/VictorMVirreiraMusicfromMexicoPart1/Mon2300.mp3'),
  ('India', 'https://ia800303.us.archive.org/30/items/VictorMVirreiraMusicfromIndia_5/ContinentalDriftMusicfromIndia02272006.mp3'),
  ('Morocco', 'https://ia902302.us.archive.org/26/items/VictorMVirreiraMusicfromMorocco/ContinentalDriftMusicfromMorocco10242005.mp3'),
  ('Kazakhstan', 'https://ia600909.us.archive.org/2/items/VictorMVirreiraMusicfromKazakhstan/ContinentalDriftMusicfromKazakhstan02062006.mp3'),
  ('Egypt', 'https://ia804500.us.archive.org/18/items/VictorMVirreiraMusicfromEgypt_0/ContinentalDriftMusicfromEgypt10312005.mp3'),
  ('Germany', 'https://ia600200.us.archive.org/14/items/VictorMVirreiraMusicfromGermany/ContinentalDriftMusicfromGermany01022006.mp3')
on conflict (country_name) do nothing;
update public.driftr_country_audio set mp3_link='https://ia800106.us.archive.org/1/items/VictorMVirreiraMusicfromNewOrleans/MusicFromNewOrleans.mp3' where country_name='United States of America' and mp3_link='https://ia801301.us.archive.org/10/items/VictorMVirreiraMusicfromNewOrleans/MusicFromNewOrleans.mp3';
notify pgrst, 'reload schema';
commit;
